### ISSUE TITLE
Documentation about sticky headers and swipe 

### ISSUE THREAD

**Issue by christophehenry** [square/cycler#41]
Hi!

The documentation states Cycler should have common features including sticky headers but I don't see it anywhere in the documentation. Am I missing something?

**Comment by luis-cortes** [comment]
I don't think it's been implemented yet. 

I would have expected to see classes like `StickyHeaderExtension` and `StickyHeaderExtensionSpec` along with an extension function like this: 

```
fun <I : Any> Recycler.Config<I>.stickyHeaders(block: StickyHeaderExtensionSpec<I>.() -> Unit) {
  extension(StickyHeaderExtensionSpec<I>().apply(block))
}
```

@helios175 Could you provide some guidance on which `RecyclerView` APIs need to be wrapped in `Extension<T>` in order to implement this feature?
